[project]
name = "trackmania_rl"
version = "0.1.0"
description = "Trackmania Reinforcement Learning"
authors = [
    { name = "Linesight" },
    { name = "Emami-IO", email = "info@emami.io" },
]
readme = "README.md"

requires-python = ">=3.10, <3.12"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "opencv-python",
    "readwritememory",
    "tminterface",
    "torchrl",
    "pygbx",
    "art",
    "python-libxdo; sys_platform == 'linux'",
    "torch",
    "torchvision",
    "pywin32; sys_platform == 'win32'",
    "rich>=14.0.0",
    "prompt-toolkit>=3.0.51",
]

[project.optional-dependencies]
doc = ["sphinx", "sphinx_rtd_theme", "sphinxcontrib.youtube"]

[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["trackmania_rl", "scripts", "game_interface"]

[tool.ruff]
include = [
    "pyproject.toml",
    "trackmania_rl/*.py",
    "scripts/*.py",
    "config_files/*.py",
]
line-length = 140

[project.scripts]
start = "scripts.start_tui:main"
train = "scripts.train:main"
